// ignore_for_file: constant_identifier_names

const String NO_INTERNET = 'لطفا اتصال به اینترنت را بررسی کنید.'; //todo
const String SERVER_ERROR = 'مشکلی پیش آمده است، لطفا بعدا تلاش کنید.'; //todo
const String OTP_ERROR = 'کد تایید وارد شده صحیح نمی باشد';
const String TRY_AGAIN_TEXT = 'تلاش مجدد';
const String PHONE_NUMBER_LABEL = 'لطفا شماره همراه خود را وارد کنید'; //todo
const String PHONE_NUMBER_HINT = '۰۹۱۲۱۲۳۴۵۶۷'; //todo
const String PHONE_NUMBER_BUTTON = 'دریافت کد'; //todo
const String PHONE_NUMBER_AGREEMENT_1 = 'ورود شما به معنای پذیرش '; //todo
const String PHONE_NUMBER_AGREEMENT_2 = 'توافقنامه کاربری'; //todo
const String PHONE_NUMBER_AGREEMENT_3 = ' است.'; //todo
const String PHONE_NUMBER_NOT_VALID = 'لطفا شماره موبایل را کامل وارد نمایید.'; //todo
const String PHONE_NUMBER_IS_EMPTY = 'لطفا شماره موبایل را وارد نمایید'; //todo
const String DATA_NOT_AVAILABLE = 'محتوای ذخیره شده ای وجود ندارد.'; //todo
const String VERIFY_CODE_LABEL_1 = 'کد تایید ارسال شده به شماره  ';
const String VERIFY_CODE_LABEL_2 = ' را وارد کنید';
const String VERIFY_CODE_HINT = '۱۲۳۴۵۶';
const String VERIFY_CODE_BUTTON = 'تایید';
const String RESEND_CODE_TEXT = 'دوباره پیامک فعال‌سازی ارسال شود؟';
const String CHANGE_PHONE_NUMBER = 'شماره را اشتباه وارد کردید؟';
const String WRONG_NUMBER_LENGTH = 'شماره موبایل باید 11 رقم باشد';
const String WRONG_NUMBER_START = 'شماره موبایل باید با 09 شروع شود';
const String VERIFY_CODE_IS_INVALID = 'کد تایید وارد شده صحیح نمی‌باشد.';
const String VERIFY_CODE_IS_EMPTY = 'کد تایید را وارد کنید.';
const String HOME_LABEL = 'خانه';
const String SERVICES_LABEL = 'سرویس‌ها';
const String PROFILE_LABEL = 'حساب کاربری';
const String LAST_TRANSACTIONS_LABEL = 'آخرین تراکنش‌ها';
const String DO_FIRST_TRANSACTIONS = 'اولین تراکنش خود را انجام دهید.';
const String PAY_THE_BILL_TEXT = 'پرداخت قبض';
const String DATE_TEXT = '۲۰:۴۵  ۱۴/۰۲/۱۲';
const String NO_ITEM_TEXT = 'هنوز تراکنشی انجام نشده است!';
const String NO_INTERNET_SPLASH = 'لطفا اتصال به اینترنت را بررسی کنید.';
const String FORCE_UPDATE = 'نسخه جدید وی‌بانک آماده است.';
const String IRANCELL = 'ایرانسل';
const String RIGHTEL = 'رایتل';
const String HAMRAH_AVAL = 'همراه اول';
const String PROFILE_DETAIL_LABEL = 'پروفایل کاربر';
const String PROFILE_FINANCE_LABEL = 'پروفایل مالی';
const String PROFILE_FRIENDS_LABEL = 'دعوت دوستان';
const String PROFILE_NOTIFICATION_LABEL = 'اعلانات';
const String PROFILE_SETTING_LABEL = 'تنظیمات';
const String PROFILE_SUPPORT_LABEL = 'پشتیبانی';
const String PROFILE_ABOUT_LABEL = 'درباره ما';
const String PROFILE_NAME_HINT = 'نام و نام خانوادگی';
const String PROFILE_DOB_HINT = 'تاریخ تولد';
const String PROFILE_NATIONAL_HINT = 'کد ملی';
const String PROFILE_GENDER_HINT = 'جنسیت';
const String PROFILE_ADDRESS_HINT = 'محل سکونت';
const String PROFILE_EMAIL_HINT = 'ایمیل';
const String EMPTY_AMOUNT = 'لطفا مبلغ را وارد کنید.';
